FROM tensorflow/tensorflow:2.15.0-gpu-jupyter

ADD . /src/nnfabrik
RUN apt-get remove -y python3-blinker
RUN pip3 install blinker==1.9.0
RUN pip3 install sphinx-rtd-theme
RUN pip3 install -e /src/nnfabrik
RUN pip3 install keras==3.0.0
RUN pip3 install optuna 
RUN pip3 install datajoint
RUN pip3 install gitpython scipy 
ENV KERAS_BACKEND="tensorflow"
WORKDIR /workspace
RUN git clone https://github.com/nihpat19/deepinterpolation.git .
RUN cd ./deepinterpolation
RUN make init
RUN python3 setup.py install



